### ISSUE TITLE
Reorganize code for github

### ISSUE THREAD

**Issue by andrejbauer** [andrejbauer/plzoo#1]
I am moving my PL zoo over to Github to make collaboration easier. The code right now is organized for publishing on my web site at http://andrej.com/plzoo, so the first thing that needs to be done is to change that.

**Comment by matijapretnar** [comment]
This issue is now probably deprecated. Should we close it?

**Comment by andrejbauer** [comment]
Wait until I get the web page working.

**Comment by andrejbauer** [comment]
Closed by c17ee999a346299abb333a97b279a1d62a955a56, 9d6554bcf1e0c3868729c0a27307e42a118b6a79, 98de319ced6c69203ffc723da2b184b8ad06ac93 and several others.
