### ISSUE TITLE
Some other languages 

### ISSUE THREAD

**Issue by act65** [andrejbauer/plzoo#10]
Don't know if this is the sort of thing you are after, but here are a couple of toy programming languages I have found.

https://github.com/m-ender/hexagony
http://norvig.com/lispy.html

**Comment by andrejbauer** [comment]
Thanks for the links. I think we've got lispy covered by the minischeme, which is waiting to be ported to PL Zoo (volunteers?). The hex thing I am not so sure about. I'd like every language to demonstrate a useful concept or a technique. What would hexagony demonstrate? That concrete synax can be insane?

**Comment by phase** [comment]
Hexagony is more of a golfing language. You can find a number of languages in the answers of [CodeGolf](http://codegolf.stackexchange.com/).
