### ISSUE TITLE
Port imperative language `comm` to the zoo

### ISSUE THREAD

**Issue by matijapretnar** [andrejbauer/plzoo#13]
Here are some old sources for an imperative language `comm`. It would be really good to port them to the zoo as we don't yet have any imperative languages in it. There are two variants, one with and one without arrays. Should we keep just the version with arrays?

[Source code for `comm`](https://github.com/andrejbauer/plzoo/files/464021/comm.zip)
[Source code for `comm` with arrays](https://github.com/andrejbauer/plzoo/files/464022/commar.zip)

**Comment by andrejbauer** [comment]
We should keep both. The zoo already contains variants of `basicLanguage`, `basicLanguage_featureX`, etc.

**Comment by andrejbauer** [comment]
Closed by 8890f2fb0b563e4a56a10efc08efef0f4404fe07
