### ISSUE TITLE
Unbound value Format.pp_print_list

### ISSUE THREAD

**Issue by edrx** [andrejbauer/plzoo#18]
When I try to compile plzoo in OCaml 4.01.0 - the version that comes
with several versions of Debian - I get these errors on boa and
lambda:

    File "src/boa/eval.ml", line 75, characters 4-24:
    Error: Unbound value Format.pp_print_list
    Did you mean pp_print_int?

    File "src/lambda/print.ml", line 9, characters 2-22:
    Error: Unbound value Format.pp_print_list
    Did you mean pp_print_int?

Here is my compilation script - note that I've adapted it to compile
each language separately so that at least some of them would work. I
set the environment variable S to ~/snarf (long story!) but S=/tmp
should work too.

    mkdir -p $S/https/github.com/andrejbauer/plzoo/archive/
    cd       $S/https/github.com/andrejbauer/plzoo/archive/
    rm   -fv $S/https/github.com/andrejbauer/plzoo/archive/master.zip
    wget      https://github.com/andrejbauer/plzoo/archive/master.zip

    rm -Rv   ~/usrc/plzoo-master/
    mkdir -p ~/usrc/
    unzip -d ~/usrc/ $S/https/github.com/andrejbauer/plzoo/archive/master.zip
    cd       ~/usrc/plzoo-master/

    make calc
    make calc_var
    make levy
    make minihaskell
    make miniml
    make miniml_error
    make miniprolog
    make poly
    make sub

    # These ones don't compile:
    make boa
    make lambda

**Comment by andrejbauer** [comment]
I think's it saf by now not to be compatible with 4.01, few people probably use that.
