### ISSUE TITLE
lambda: missing reduction of terms with free variables

### ISSUE THREAD

**Issue by asr** [andrejbauer/plzoo#33]
Great repository. Thanks @andrejbauer.

I want to play with different reduction strategies in the `lambda` language. Using the canonical example `(λy.z) Ω` where  `Ω = (λx. x x) (λx. x x)` I got the error:

```
lambda -- programming languages zoo
Type Ctrl-D to exit.
(^y . z) ((^x. x x) (^x. x x))
Error at line 0, characters 6-7:
unknown identifier z
```

So, it seems in `lambda` the reduction only work combinators (i.e. terms without free variables).

**Comment by andrejbauer** [comment]
If you want to use `z` freely, i.e., not a bound variable, you should first declare it a `constant`:

```
lambda> :constant z
z is a constant.
lambda> (^y . z) ((^x. x x) (^x. x x))
z
```

(This is so that typos don't go unnoticed, and generally to follow the principle that identifies shouldn't appear out of thin air.) Another option is to just do it under an abstraction over `z`:

```
lambda> :deep
I will evaluate deeply.
lambda> ^z . (^y . z) ((^x. x x) (^x. x x))
λ z . z
```

**Comment by asr** [comment]
I see. Thanks!
