### ISSUE TITLE
Equip source code with locations

### ISSUE THREAD

**Issue by matijapretnar** [andrejbauer/plzoo#5]
Here is a checklist of languages annotated with locations:

- [ ] `boa`
- [ ] `calc`
- [ ] `calc_var`
- [x] `lambda`
- [x] `levy`
- [ ] `minihaskell`
- [x] `miniml`
- [x] `miniml_error`
- [ ] `miniprolog`
- [ ] `poly`
- [ ] `sub`

I guess not all need to be annotated. For example, `calc` is supposed to be the most basic one in the bunch, and adding annotations goes against its purpose. What about the rest?

**Comment by andrejbauer** [comment]
Some should be annotated, but not all. Which languages use locations now?

**Comment by matijapretnar** [comment]
I've now updated the list to show all languages.

**Comment by andrejbauer** [comment]
I'd say that's quite enough. Anyone who wants to see locations can look at four examples. Perhaps we can strive to have future languages use locations. Close?

**Comment by matijapretnar** [comment]
I agree.
