### ISSUE TITLE
Avoid read_more

### ISSUE THREAD

**Issue by matijapretnar** [andrejbauer/plzoo#6]
Currently, `Zoo.LANGUAGE` includes `read_more : string -> bool`, which is used in the interactive toplevel to determine whether further lines should be read before the input is parsed. I vaguely remember that I have seen this resolved automatically, though I do not remember how and where. Any ideas?

**Comment by andrejbauer** [comment]
We have no good reason to have `read_more`, except to demonstrate that it's doable. But I think that's a good reason. So perhaps we can just make it more uniform: if the line ends with `\` this implies "read more".

**Comment by matijapretnar** [comment]
Yes, that seems a simpler idea. The other one probably requires changing the parser to propagate errors in a better way.
