### ISSUE TITLE
Toplevel directives

### ISSUE THREAD

**Issue by matijapretnar** [andrejbauer/plzoo#8]
Some languages already supported directives such as `#help` , `#quit`, `#load file_name` and `#reset` (to reset the initial environment), but they were dropped when migrating to the new interface. Which ones should we support? I guess `#help` should be useful, especially if each language came with a short help message that lists the possible toplevel commands.

**Comment by andrejbauer** [comment]
If we start supporting directives systematically, we should actually think about another, more global way of organizing a language. There are several stages:

* lexing
* parsing
* macro-expansion and/or top-level directives
* syntax desugaring
* type checking
* evaluation

Each of these in general has its own environment (see how Andromeda works). The top-level directives are just one such stage. So we need to think about demonstrating the stages a bit more systematically (and not necessarily in every language).

**Comment by matijapretnar** [comment]
I was thinking that the toplevel lives on the outside and is the user interface to the language, which then covers everything from lexing to evaluation. Directives are just a part of that interface, in the same way as loading of files or the prompt.

**Comment by andrejbauer** [comment]
Except that there are directives which are not like that (see `lambda`).

**Comment by matijapretnar** [comment]
@andrejbauer and I discussed this in person. We decided to not add directives because adding them would just bloat the code. `#help` is already written in the `README`, you can `#quit` using EOF character (and the user is informed of this when running the file), you can `#load` a file by passing an argument, and you can `#reset` by quiting and restarting the program.
